### ISSUE TITLE
Inconsistent phi value after select based on undef value

### ISSUE THREAD

**Issue by FlashSheridan** [AliveToolkit/alive2#1008]
# Summary:
The Alive2 Compiler Explorer report https://alive2.llvm.org/ce/z/2H7VKt seems to be complaining incorrectly about a value mismatch in our optimization.  It is clearly giving an incorrect value for the variable %value, received from a phi instruction after a select based on undef value.

# Actual Behavior

At the end of the “ERROR: Value mismatch” section of https://alive2.llvm.org/ce/z/2H7VKt, the Target %value is supposedly #x9 (9, -7), which is inconsistent with the previously given values.  The optimized source for the assignment to %value is

```%value = phi i4 [ 0, %entry ], [ %spec.select, %addmod ] ```
Obviously the 0 value from %entry is different from #x9.  The value of %spec.select from %addmod is given two lines earlier:  i4 %spec.select = #x1 (1), which is also not #x9.

# Expected Behavior
We’re not confident in what the expected behavior is.  Alive2 notes, reasonably, that in both src and tgt, %obit is based on undef value.  Thus the value of %spec.select might have been different, but Alive2 proclaimed it to be #x1.

`lli` on the attached file, which has some code added for printing, says the return value is 1 for src and 0 for tgt. (With poison rather than undef, both return 0.)

Discovered by @vladimirradosavljevic
# Configuration
Alive2 Compiler Explorer version v0.0-2228-ge3b5f7e
Safari 17.3 (18617.2.4.11.9)
MacOS 13.6.4 22G513 on M1 Max
Similar behavior (though with different choice of counterexample literals) with my local `alive-tv` (b13ec126) and LLVM 18 (8f6f5ec), so this is not a symptom of https://github.com/AliveToolkit/alive2/issues/986.

[2H7VKt.ll](https://github.com/AliveToolkit/alive2/files/14091171/2H7VKt.ll.txt)

**Comment by regehr** [comment]
well... if Alive is happy with the transformation under the `--disable-poison-input` then maybe just call it good? there are certainly a number of things in the tree already that don't work when inputs are undef

also, this is a pretty big example to think about and I can't llvm-reduce it since you're providing both the src and tgt. can you llvm-reduce it under the criterion that Alive reports a value mismatch and post the results here?

**Comment by regehr** [comment]
I don't know if you are an llvm-reduce user but if not, this is the interestingness test that you want, but obv adjust the path 
```
#!/bin/bash
timeout 1 $HOME/alive2-regehr/build/alive-tv $1 2>&1 | grep 'Value mismatch'
```

**Comment by nunoplopes** [comment]
The optimization is not correct for undef inputs. Each time an undef is used it can yield a different value.
Since `%obit` in tgt is undef, the select can return either of the operands each time it is used. I know the counterexample may look confusing because you get a value for the select and a different for the phi, but that's just how undef works!

**Comment by FlashSheridan** [comment]
> The optimization is not correct for undef inputs. 

Thanks for the explanation in the [subsequent issue](https://github.com/AliveToolkit/alive2/issues/1009), which may have revealed an important bug in our code; but that’s not the point to this bug:


>>  We’re not confident in what the expected behavior is.  Alive2 notes, reasonably, that in both src and tgt, %obit is based on undef value.  Thus the value of %spec.select might have been different, but Alive2 proclaimed it to be #x1.
 
 
> Each time an undef is used it can yield a different value. Since `%obit` in tgt is undef, the select can return either of the operands each time it is used. 

The issue may be in the Alive2 UI for values, especially those not marked “[based on undef value],” but `%obit` and `%spec.select` are each used only once (and the value for `%spec.select` (`#x1`) is not marked as based on undef value).  If the display of `%spec.select = #x1` is not relevant to Alive2’s assumption for the value’s sole use in the chosen counterexample, I’m misunderstanding the UI.

**Comment by nunoplopes** [comment]
> The issue may be in the Alive2 UI for values, especially those not marked “[based on undef value],” but `%obit` and `%spec.select` are each used only once (and the value for `%spec.select` (`#x1`) is not marked as based on undef value). If the display of `%spec.select = #x1` is not relevant to Alive2’s assumption for the value’s sole use in the chosen counterexample, I’m misunderstanding the UI.

I understand the frustration. The issue is that it's quite expensive to mark things as based-on-undef. We use a cheap technique, but it cannot detect all cases. It's annoying, but I don't think we want to spend several minutes to print a counterexample.
Our hope was that we would remove undef from LLVM altogether. That's the main reason why I haven't invested much in making undef perfect in Alive2.

I hate to say this, but in the end this project is maintained by poorly paid academics, while the users are handsomely paid compiler developers. Moreover, companies are not willing to sponsor Alive2. While I try to fix most bugs that come our way, I prioritize the things that are useful for the majority of the users and for my own research. My priority is to remove undef from LLVM.

**Comment by FlashSheridan** [comment]
I quite understand your point (Matter Labs is [hiring](https://jobs.eu.lever.co/matterlabs), and my wife is a professor).  Alive2 has done a lot of good for the LLVM community and for our compiler, so we’d like to become a sponsor; please send me the details.
        We’ve now fixed our `undef` bug; I’m not sure where it would fit in your [BugList.md](https://github.com/AliveToolkit/alive2/blob/master/BugList.md).  It’s our PR#385, and will become open source when we update our public repo, though the PR number may be transient.

**Comment by FlashSheridan** [comment]
> …I haven't invested much in making undef perfect in Alive2.

That makes sense, and it’s no longer crucial for us, given the freeze fix plus using `noundef` where needed.  I would suggest, for others still depending on `undef`, tweaking the UI (or perhaps the documentation) to make it clearer what the user can’t rely on when analyzing an unsoundness report involving `undef` — or perhaps just remove some of the output.  (I don’t understand the reports well enough to submit a ReadMe PR.)
