### ISSUE TITLE
Source and Target Example Values Diverge Before Source Code Does

### ISSUE THREAD

**Issue by FlashSheridan** [AliveToolkit/alive2#1009]
# Summary
In the Alive2 Compiler Explorer report  https://alive2.llvm.org/ce/z/Kc-R5t, the values start to differ while the corresponding source is still the same.  The Target section ends with “UB triggered on br,” while the Source section does not; this may be unfair to our optimization, as Alive2 seems wrong _not_ to complain of UB in the source.

# Actual Behavior
(1) In the the excerpt below from the “Source:” subsection of the “ERROR: Source is more defined than target” section of the Alive2 Compiler Explorer report  https://alive2.llvm.org/ce/z/Kc-R5t, %arg1m is marked “[based on undef value].” 

```i4 %arg1m = #x0 (0) [based on undef value]```

The corresponding entry for the Target is not so marked, though both get the value #x0.  The impact of this is unclear, but any divergence at that point seems improper, since the src and tgt code are identical up to that point.

(2) Later there’s a contrary divergence (below) for %sum.mod, where only the target has “[based on undef value],” though it seems that %sum.mod is based on undef in both source and target: it depends ultimately on %arg1, which is chosen as undef for the counterexample.  

``` i4 %sum.mod = #x0 (0)	[based on undef value]```

(3) The “UB triggered on br” at the end of the Target section seems accurate, since the code branches based on %obit, which also depends on %arg1.  But it seems unfair, since the identical branch instruction in the source is also based on %obit, which depends on  on %arg1, though in a superficially different way due to the optimization.  

# Expected Behavior
I think the high level behavior should be to accept that our optimization does not make the behavior undefined, as it already was.  The value annotations should be identical as long as the code remains identical.  After that, I am less confident. 

I added some code to get `lli` to print out the return values of both src and tgt (attached); they differ when passed undef (1 vs. 2), but allowably so, given the nature of undef. (Both return 2 when passed poison instead of undef.)

Discovered by @vladimirradosavljevic
# Configuration
Alive2 Compiler Explorer version v0.0-2228-ge3b5f7e
Safari 17.3 (18617.2.4.11.9)
MacOS 13.6.4 22G513 on M1 Max
Similar behavior (though with different choice of counterexample literals) with my local `alive-tv` (b13ec126) and LLVM 18 (8f6f5ec), so this is not a symptom of https://github.com/AliveToolkit/alive2/issues/986.

[Kc-R5t.ll](https://github.com/AliveToolkit/alive2/files/14091282/Kc-R5t.ll.txt)

**Comment by nunoplopes** [comment]
I'm sorry to say but the optimization is indeed incorrect when `%arg1` is undef. You can see that Alive2 proves it correct if you add `noundef` to the first argument.
This is because `@llvm.uadd.with.overflow` does the addition and overflow check with the same value, while if you lower it into add+icmp, each operation may observe different values for `%arg1m` (undef can yield a different value each time it is used).

Take the counterexample, where `%modulo = #x3`.
Then `%arg1m` and `%arg2m` must be in `[0,2]` and so their sum never overflows. So 

I know the counterexample isn't too easy to read. But the optimization is incorrect.

**Comment by vladimirradosavljevic** [comment]
Thank you @nunoplopes for your response!
What puzzles me is that `@llvm.uadd.with.overflow` will be convert to the `add` + `ult` during selection phase, so does that mean we can get the same problem with `undef` like here?

**Comment by nunoplopes** [comment]
> Thank you @nunoplopes for your response! What puzzles me is that `@llvm.uadd.with.overflow` will be converted to the `add` + `ult` during legalization phase (LLVM common code is responsible for this), so does that mean we can get the same problem with `undef` like here?

No one said that LLVM was correct 🙂
Legalization at the end of the pipeline, so in practice it may not matter since assembly doesn't have undef. SDAG does have undef & poison, so I'm not saying everything is great, but the chances of miscompilations is low.
That's not true if done in the middle of the optimization pipeline. But these days. clang adds noundef to most (all?) function arguments, so it's relatively easy to ensure something isn't undef. You can also use `freeze`.
