### ISSUE TITLE
issue with attribute inference for operator new

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#1134]
I don't know that there's a problem with Alive here, but I could use a set of eyes on this to help figure out if we should solve this on the Alive side or on the lifter side. or maybe we just ignore this, it doesn't seem like a super important case (but I do keep running across this while looking for real bugs).

I can perfectly well validate the AArch64 backend's translation of this code:
```llvm
declare nonnull ptr @f(i64)

define ptr @f() {
  %1 = tail call ptr @f(i64 0)
  ret ptr %1
}
```
however, when the function is the operator new, I get a refinement failure since attribute inference keys on the name of the function. so I can't validate the translation of this one:
```llvm
declare nonnull ptr @_Znwm(i64)

define ptr @f() {
  %1 = tail call ptr @_Znwm(i64 0)
  ret ptr %1
}
```
the lifted code ends up being:
```llvm
define ptr @f() local_unnamed_addr {
arm_tv_entry:
  %0 = tail call ptr @_Znwm(i64 0)
  ret ptr %0
}

; Function Attrs: nofree
declare ptr @_Znwm(i64) local_unnamed_addr #0

attributes #0 = { nofree }
```

alive expands this out to:
```
declare ptr @_Znwm(i64) nonnull

define ptr @f() {
#0:
  %#1 = tail call ptr @_Znwm(noundef i64 0) nonnull nofree noundef noalias willreturn alloc-family(_Znwm) allockind(alloc, uninitialized) allocsize(0) memory(inaccessiblemem: readwrite)
  ret ptr %#1
}
=>
declare ptr @_Znwm(i64) nofree

define ptr @f() asm {
arm_tv_entry:
  %#0 = tail call ptr @_Znwm(noundef i64 0) nofree noundef noalias willreturn alloc-family(_Znwm) allockind(alloc, uninitialized) allocsize(0) memory(inaccessiblemem: readwrite)
  ret ptr %#0
}
```
and then there's a refinement failure

**Comment by nunoplopes** [comment]
Not sure what to do with this one.
The `nonnull` attribute on `_Znwm` is wrong, since the `new` operator can return null.
One way to fix this is to make the source function UB. But the code isn't really written in a way that makes this easy. It unions flags, but does not replace or check them. That's a non-trivial refactor.
Also, we don't differentiate between attributes in the call site or in the declaration. We can only make UB the wrong attributes on the decl, not on the call. So while we would fix this particular program, it could still trigger elsewhere.

Is the source code generated by a fuzzer, or is it real code?
What if we just copied all decl attributes in assembly mode? Or does the lifter already do something along those lines?

**Comment by regehr** [comment]
this is reduced from something in the LLVM unit test suite.

I copy some attributes from src to tgt, but not all. I've been just sort of doing them on a case by case basis, when it seemed useful and appropriate.

if there's not an obviously good way for you to fix this, let's not worry about it, I'll fix this on my side if it becomes annoying enough
