### ISSUE TITLE
Treating a global variable with numeric assigned as its name

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#209]
Transforms/SimplifyCFG/branch-fold-dbg.ll has a global variable with numeric name assigned, and llvm::GlobalVariable::getName() returns a nonsense value.
This causes llvm::Module::getGlobalVariable() at llvm2alive.cpp fail and return null.

```
@0 = external hidden constant [5 x ...], align 4
...
```

Possible workaround is to not use the Module::getGlobalVariable() & make Alive2's GlobalVariable maintain which LLVM's global variable it was created from. Would this solution work?

**Comment by nunoplopes** [comment]
The problem with unnamed constants is that they may change their number, since the number is just the order in which they appear in the file.
We can try to ignore this and see how it goes. I guess we can just iterate over all globals and count the unnamed ones every time a new GlobalVariable is created.

**Comment by aqjune** [comment]
I see, I'll have a look.
