### ISSUE TITLE
enhancement: TV dashboard

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#41]
Nuno and I discussed this briefly; I'd like to use this space to iron out a few details and then I'll start working on code.

The goal is to make it easy for people to see the results of a translation validation run, whether it is over the LLVM test suite or some other collection of LLVM IR.

There are maybe three steps:

1. Run Alive2 TV on some test cases using a special command line option that causes it to emit extra details about its run. This could go to its stderr stream or it could write a bunch of special files, I'm not sure which makes more sense.

2. Run a not-yet-implemented script which has two outputs. First, a web page showing the results of the TV run, with links to test cases, details, etc. Second, a CSV file (or similar) describing the outcome of each test case. I don't think it's worth interacting with a database or anything heavyweight here.

3. Optionally, run another not-yet-implemented script that diffs two (or more?)
 TV runs using the CSV summary files. This script emits a web page that describes all of the test cases that had a different outcome across the input runs.

If I'm the only one working on this I'd prefer to work in Perl, which I find much easier and more concise than Python. But if that seems like a bad idea I can muddle along in Python. Let me know what you think about all this.

**Comment by nunoplopes** [comment]
I think it would be nice to keep some history to see how LLVM+Alive evolve over time, like number of crashes of Alive, number of covered functions, number of failed functions, etc.
Also, a functionality to tag failures would be cool. Like select-poison-bug, ok-if-undef-gone, alive-bug, etc.

Run time of Alive would be interesting as well. Not for the unit tests per se, but when running on larger programs. For now we can stick with the single-file large programs because we don't integrate with clang yet.

I'm fine with Perl if you take the bulk of the development work :)  I haven't done anything in Perl in more than a decade, so I can only fix bugs and do minor things.

**Comment by nunoplopes** [comment]
Anyway, I think anything is better than what we have right now, which is nothing :)  Development is still a bit blindfolded.  (well, and at some point we need to collect numbers for a possible paper -- not the priority now; just to keep in mind).

**Comment by regehr** [comment]
ok, thanks Nuno!
I agree with all this
I think the only thing for you to do is (whenever you feel like it) put more verbosity into alive output so when I go to scrape this stuff, it's all there

**Comment by nunoplopes** [comment]
We have something now. Will be improved over time.
