### ISSUE TITLE
Incorrect result when select(freeze undef) is given

### ISSUE THREAD

**Issue by aqjune** [AliveToolkit/alive2#450]
```
declare void @foo_i8(i8)

define void @src(i8 %x, i8 %y) {
entry:
  %cond.fr = freeze i1 undef                                                        
  %s = select i1 %cond.fr, i8 %x, i8 1                                             
  %s2 = select i1 %cond.fr, i8 1, i8 %x                                            
  call void @foo_i8(i8 %s)                                                          
  call void @foo_i8(i8 %s2)                                                         
  ret void                                                                          
}

define void @tgt(i8 %x, i8 %y) {
entry:
  call void @foo_i8(i8 1)                                                          
  call void @foo_i8(i8 1)                                                         
  ret void                                                                          
}
```

This transformation is incorrect, but Alive2 says `Transformation seems to be correct!`.

**Comment by aqjune** [comment]
This seems to be an issue of a function call encoding. If `ret (add %s1 %s2)` is used in src instead, and `ret 2` is used in tgt, it successfully finds a counter example.

**Comment by aqjune** [comment]
Relevant test: https://alive2.llvm.org/ce/z/hzwzM_

**Comment by aqjune** [comment]
I'll have a look at this issue.

**Comment by regehr** [comment]
this is interesting. it would be really nice if we didn't have to discover these by hand. maybe I should look into some sort of fuzzer that could help here?

a problem is that using differential testing, it will be hard to distinguish between boring LLVM bugs and exciting alive2 bugs. not sure what to do about that yet...

**Comment by aqjune** [comment]
IMO, it would be a great opportunity to guarantee Alive2's correctness to a certain level. What do you think @nunoplopes ?
For finding false negatives, I don't have a concrete idea yet..
To find false positives, considering identical inputs was enough sometimes. Alive2 supports various function attributes/metadata, but their combinations weren't deeply explored yet.

**Comment by regehr** [comment]
there's a piece of infrastructure we're lacking here, which is an UB-aware LLVM interpreter. given this, I can build us ways to test for both false alarms and missing alarms. without it, I'm not sure that we can do serious randomized testing.

**Comment by regehr** [comment]
actually the UB-aware interpreter doesn't seem as helpful as I had thought. my idea had been to model poison accurately (of course that's easy) and to resolve undefs to a random value that is under control of a fuzzer. so whatever smarts the fuzzer has, it'll use to try to discover nasty values for the undefs. I was naively thinking that this would only miss bugs, and not raise false alarms. however, that doesn't work for undefs in the target function. if I'm correct here, the randomized UB-aware interpreter will both miss bugs and also incorrectly signal bugs, because there's just no way to check refinement accurately using this approach. does that all make sense?

**Comment by nunoplopes** [comment]
Most of the bugs we have seen so far are around incorrect axioms and/or incorrect variable quantification. These are theoretically tricky, and they happened because sometimes we didn't fully spell out the formulas by hand before implementing them.
Most of the tricky axioms come from function calls. I'm also aware of an issue with `assume`.
Just to say that issues with the semantics are usually caught very early, either with LLVM's unit tests or our unit tests. Maybe just fuzzing function calls (with memory operations perhaps) is sufficient to make Alive more robust. Maybe test identical pairs and have a way to remove function calls from reachable branches and make sure that Alive catches that as incorrect transformation?

**Comment by regehr** [comment]
yeah it seems reasonable to focus on specific areas of the semantics, if we don't have a good story for general-purpose fuzzing. I could add function calls to opt-fuzz, for example, and perhaps also a differential fuzzing mode where it generates pairs of known-equivalent or known-inequivalent functions

**Comment by regehr** [comment]
but I'm depressed if we can't create a refinement checker out of an UB-aware interpreter. I had been hoping to use such a thing to look for bugs in loop transformations that are out of reach for alive2.

**Comment by aqjune** [comment]
I found that Vellvm has an interpreter that supports UB.
```
$ ./vellvm -interpret div-by-zero.ll 
(* -------- Vellvm Test Harness -------- *)
Processing: div-by-zero.ll
Fatal error: exception Failure("Undefined Behaviour: Unsigned division by 0.")
```
If we have an interpreter that allows a register to have a set of value in addition to a single value, refinement check would be easier.
However, it seems Vellvm's interpreter does not support that, and also it will make the search space large, so it wasn't clear whether this is a cost-effective direction...

**Comment by aqjune** [comment]
After #3 is resolved, this should be resolved too.

Consider this example:

```
define i1 @src() {
  %cond.fr = freeze i1 undef
  call void @foo(i1 %cond.fr) ; Output memory of this call: msrc
  ret i1 %cond.fr
}

define i1 @tgt() {
  call void @foo(i1 0)        ; Output memory of this call: mtgt
  ret i1 1                    ; this is incorrect, but Alive2 says ok
}
```

It is incorrect, but Alive2 says ok (https://alive2.llvm.org/ce/z/JaNMZC ).
Note that this problem cannot be solved by properly setting UB of foo(); if either foo(0) or foo(1) raises UB, by nondet. execution, src always has UB.

The reason is as follows.
A precondition for src/tgt's foo call is as follows:
undef = 0 -> msrc = mtgt

A refinement formula is:
undef = 1 /\ msrc = mtgt

Finally, the VCGen generated by Alive2 is like this:
∀ undef, (undef = 0 -> msrc = mtgt) /\ ~(undef = 1 /\ msrc = mtgt)

This forall is always false regardless of msrc and mtgt.
- If msrc = mtgt, the formula is '∀ undef, ~(undef = 1)'.
- If msrc != mtgt, it is '∀ undef, (undef = 0 -> false)'.

I think the source of this problem is that the output of the source's memory (msrc) does not take undef into consideration.
Again, skolemization can resolve this problem in theory.
To make a counterexample, I think having an one-byte extra memory block is sufficient, which should be skolemized. The remaining memory blocks don't need to be skolemized

**Comment by nunoplopes** [comment]
My current plan of attack is to skolemize undef variables. The issue is that the original refinement formula is:
∀ I, O, F . (∃N . P'(I, F, N, O)) ⇒ (∃N . P(I, F, N, O))

Where F is the set of functions used. The easiest way to deal with those existentials is to skolemize them. The current mistake we do is that we cross the quantified F vars across the existential incorrectly.
Let's see how bad perf gets.. The advantage is that most quantifiers then go away.

**Comment by aqjune** [comment]
Could you explain slightly more details, please?
Does it mean that N_src(undef vars in src) can be skolemized like N_src = f(N_tgt)?
What if N_tgt is an empty set? In the example in the above comment, tgt has constants only, so N_tgt might be an empty set.

**Comment by nunoplopes** [comment]
see also https://github.com/AliveToolkit/alive2/pull/490
fn calls need to check for increased undefinedness of arguments.
