### ISSUE TITLE
[Loops] need to look at 2nd iteration so that phi nodes take back edges into account

### ISSUE THREAD

**Issue by LebedevRI** [AliveToolkit/alive2#475]
I suspect it may be a duplicate of some existing issue, but still
```
declare i1 @geni1()

declare void @use(i4)

define void @src(i4 %val_left, i4 %val_right, i4 %val_middle, i1 %c0) {
entry:
  br i1 %c0, label %left, label %right

left:
  br label %middle

right:
  br label %middle

middle:
  %i0 = phi i4 [ %val_left, %left ], [ %val_right, %right ], [ %val_middle, %middle ]
  %i1 = phi i4 [ %val_left, %left ], [ %val_right, %right ], [ %i1, %middle ]
  call void @use(i4 %i0)
  call void @use(i4 %i1)
  %c1 = call i1 @geni1()
  br i1 %c1, label %end, label %middle

end:
  ret void
}
define void @tgt(i4 %val_left, i4 %val_right, i4 %val_middle, i1 %c0) {
entry:
  br i1 %c0, label %left, label %right

left:
  br label %middle

right:
  br label %middle

middle:
  %i1 = phi i4 [ %val_left, %left ], [ %val_right, %right ], [ %i1, %middle ]
  call void @use(i4 %i1)
  call void @use(i4 %i1)
  %c1 = call i1 @geni1()
  br i1 %c1, label %end, label %middle

end:
  ret void
}
```
alive2 says `Transformation seems to be correct!`

But how can it be so?
We've completely dropped uses of `%val_middle`?

**Comment by nunoplopes** [comment]
The transformation is wrong, I agree.
To prove it wrong we need to look at at least the 2nd iteration of the loop. Alive2 currently only analyzes the 1st iteration of each loop. This is a well known issue and will get fixed within a few months (famous last words 😀).
I'm leaving this open so we can collect incorrect loop tests.

**Comment by nunoplopes** [comment]
CC @kevindevos

**Comment by kevindevos** [comment]
I also agree with @nunoplopes . 
I'm working on loop unroll which should let Alive check more than just the first iteration. This also reminds me that i need to look at single node loops, not sure if what i have so far handles that correctly. Interestingly unroll may also lead to adding multiple phis in nodes that did not have one before unroll, which has been complicating things a bit. Simple example::

```
define i32 @test1(i32* %var) {
entry:
  %cond = icmp eq i32* %var, null
  br label %header

header:
  %phi_indvar = phi i32 [0, %entry], [%indvar, %loop]
  br i1 %cond, label %loop, label %exit

loop:
  %indvar = add i32 %phi_indvar, 1
  br label %header

exit:
  ret i32 %phi_indvar
}
```
exit will have a phi in the second iteration for selecting between %phi_indvar from header or from the duplicated version of header since exit would then have two edges from two different versions of the header block.

**Comment by regehr** [comment]
wow, will be super cool having multiple loop iterations!

**Comment by nunoplopes** [comment]
This should be working now.
