### ISSUE TITLE
Semantics of readnone function calls is wrong

### ISSUE THREAD

**Issue by fhahn** [AliveToolkit/alive2#477]
It seems like function calls to `readnone` functions lead Alive2 to verify invalid transformations as correct.

The example below verifies as correct if `%f.1` is replaced by `true`, which is *not* correct, as it is always `false`.

If the first call to `@use` is removed, Alive2 correctly rejects the transformation as invalid. The use of functions to insert uses to check is quite common in LLVM tests and this could lead to invalid transformations to not being flagged up.

Full example: https://alive2.llvm.org/ce/z/9agPfJ
```
declare void @use(i1) readnone

define void @src(i32 %x, i32 %y) {
entry:
  %c.1 = icmp ule i32 %x, %y
  br i1 %c.1, label %bb1, label %bb2

bb1:
  ret void

bb2:
  call void @use(i1 true)
  %f.1 = icmp ule i32 %x, %y
  call void @use(i1 %f.1)
  ret void
}
```

**Comment by nunoplopes** [comment]
Ok, I see what's the issue: src calls already `use(true)` so in terms of UB that gets covered (assuming that readnone functions trigger UB for the same set of inputs).
src also calls `use(false)` but the target doesn't. This is ok because if anything we are removing UB. Calling `use(true)` instead doesn't add any more UB. See this example where Alive2 also says it's correct (introduction of fn calls to readnone): https://alive2.llvm.org/ce/z/r-F8_i
Removing fn calls also works: https://alive2.llvm.org/ce/z/T2MqPy

We may have an issue with the understanding of the semantics (there's even a TODO in the code 😀). To summarize:
 - Can readnone calls be removed? If not, why?
 - Can readnone calls be inserted? If not, why?
 - (extra question): do readnone functions always return? (if not we can't introduce them)

My understanding was that readnone functions are pure (only depend on the inputs) and don't modify any state. Hence you could remove & add them. If they can modify some state, then we need to understand what's the exact semantics.
Any suggestions/opinions/examples on the above?  I'm of course happy to implement whatever the right thing is 😀

**Comment by fhahn** [comment]
Ah, I think I see what is going on with my original test case. Alive is basically ignoring/removing the second `@use` call because it does not modify any state and the result is not used?

One thing to note is that `readnone` is limited to memory visible to the program. In some places in the LangRef also just mention visible to to caller and explicitly call out that there could be an unwind implementation that does not use memory accessible by the caller.

Intersting questions, below my interpretations:

> Can readnone calls be removed? If not, why?

`readnone` calls may unwind, so removing them would mean that we change the behavior of the program.

> Can readnone calls be inserted? If not, why?

I think no, same reasoning as above.

> (extra question): do readnone functions always return? (if not we can't introduce them)

I don't think so, they can either unwind or may never return, unless `willreturn` is also specified.


With those answers, I think it would still be possible to remove/ignore subsequent calls to `@use` if it is called with both `true`/`false` beforehand.

**Comment by nunoplopes** [comment]
> Ah, I think I see what is going on with my original test case. Alive is basically ignoring/removing the second `@use` call because it does not modify any state and the result is not used?

Exactly!


> With those answers, I think it would still be possible to remove/ignore subsequent calls to `@use` if it is called with both `true`/`false` beforehand.

Ok. I agree with you on inserting new function calls. But I'm a bit puzzled regarding fn call removal.
Reading [LangRef](https://llvm.org/docs/LangRef.html#function-attributes) again, I found this interesting statement: "(...) and never changes any state visible to callers"
Does that imply that it can read and write, e.g., some static function variable? Or is that visible to the callers in the form of when called twice with the same input the function can return different values?
Is the following correct?
```
%x = call @use(1)
%y = call @use(1)
=>
%x = call @use(1)
%y = %x  ; RAUW
```

I really can't figure it out based on what's written in LangRef. I guess we need to review how `readnone` is used by optimizers.

**Comment by aqjune** [comment]
GVN seems to merge two readnone calls into one: https://godbolt.org/z/b7Wf14

**Comment by fhahn** [comment]
> Is the following correct?
> %x = call @use(1)
> %y = call @use(1)
> =>
> %x = call @use(1)
> %y = %x  ; RAUW

I *think* that should be allowed.

I think it would be good to clarify the wording of read none at least. In the first paragraph, it says accessing any mutable state *visible to the caller* is UB. In the last paragraph, it says it is UB to read/write any memory visible to the *program*.

With the wording from the first paragraph, it seems like reading some static memory and reading memory only visible to the function locally is OK.

**Comment by aqjune** [comment]
> With the wording from the first paragraph, it seems like reading some static memory and reading memory only visible to the > function locally is OK.

`-function-attrs` attaches `readnone` to a function that reads/writes to a function-local memory: https://godbolt.org/z/1TnvvM
For a static memory, it doesn't seem to do so. My impression from GVN is that people wanted to think a readnone function as simply a pure function.

In my opinion, if we're rewriting LangRef, it might be easier to describe what is *allowed* to readnone functions, rather than describe what is *disallowed* to them. The definition of 'a mutable state visible to the caller' doesn't seem straightforward to me.

**Comment by aqjune** [comment]
A relevant input reduced from gzip: 
[input.srctgt.ll.zip](https://github.com/AliveToolkit/alive2/files/5468780/input.srctgt.ll.zip)
Investigating the reason

**Comment by nunoplopes** [comment]
That test case show that LLVM isn't behaving according to LangRef. A readnone function isn't allowed to change any "internal" state as LangRef suggests, otherwise the transformation below that is being done wouldn't be legal:
```llvm
%a = call @f() readnone
%b = call @f() readnone
  =>
%a = call @f() readnone
%b = %a
```

**Comment by fhahn** [comment]
>  A readnone function isn't allowed to change any "internal" state as LangRef suggests, otherwise the transformation below that is being done wouldn't be legal:

IIUC that is the intended meaning.

**Comment by aqjune** [comment]
A relevant issue: LLVM lowers switch into constant array+lookup, but it still preserves the readnone flag.
[readnone.zip](https://github.com/AliveToolkit/alive2/files/5899954/readnone.zip)
This pair came out while running translation validation on ph7.
Due to the readnone flag in the target, validation fails.

LangRef says:

> On a function, this attribute indicates that the function computes its result (or decides to unwind an exception) based strictly on its arguments, without dereferencing any pointer arguments or otherwise accessing any **mutable state** (e.g. memory, control registers, etc) visible to caller functions.

> ...

> If a readnone function reads or writes memory visible to the program, or has other side-effects, the behavior is undefined. If a function reads from or writes to a readnone pointer argument, the behavior is undefined.


The last statement is slightly unclear, but since the first statement says accessing 'mutable state' isn't allowed, should we interpret constant globals as not-a-part-of mutable state?

**Comment by nunoplopes** [comment]
All seems to be covered now, except for Juneyoung's last example of a readnone function reading a constant global. I guess we can allow that as it's equivalent to code.
