### ISSUE TITLE
is undef UB for memory operations' size & ptr?

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#488]
Is it UB to give a non-deterministic value to the size and/or ptr argument of memory operations, such as:
- load
- store
- memcpy
- memset

What about stdlib?
- memcmp
- strlen

**Comment by nunoplopes** [comment]
@aqjune

**Comment by aqjune** [comment]
https://reviews.llvm.org/D87994

**Comment by aqjune** [comment]
If load/stores' pointers are always well-defined, we should define memcmp/strlen's pointers to be well-defind as well, I think.
The reason is that instcombine/expandmemcmp/... performs memcmp/strlen -> load+icmp. If it is UB for load to have partially undefined ptrs, so should memcmp/strlen be.

**Comment by aqjune** [comment]
The discussion is moving towards allowing dereferencing pointers with undef bits, but I think we're okay - `strip_undef_and_add_ub` adds UB when the value can be *fully* undef, and dereferencing fully undef was already UB because it can be null. So, we're already okay.
Same to the the sizes of memset/memcpy here: the size cannot be fully undef because it can overflow the size of the memory block.

**Comment by aqjune** [comment]
Maybe it is okay to close this issue now?

**Comment by aqjune** [comment]
To leave a record: there was a second patch (https://reviews.llvm.org/D95238) which changed the semantics of dereferencing undef-y pointers to raise UB.
