### ISSUE TITLE
Clarify semantics of malloc

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#503]
We got a regression in `tests/alive-tv/memory/malloc-noundef.srctgt.ll` because malloc returns a non-deterministic value based on an undef value if such is passed as input:
```
  %p = malloc i64 %sz
  %p.fr = freeze * %p
  call void @f(* %p.fr)
=>
  %p = malloc i64 %sz
  call void @f(* %p)

%p = (ite (or malloc_never_fails
         (and (= #b0 ((_ extract 63 63) (ite (= #b0 isundef_%sz) %sz
undef!2)))
              |#alloc_nondet_nonnull!3|))
     #b100000
     #b000000)
```

If size is undef, the return value can be either zero or an allocated object.
Solutions for this include:
 - don't change anything
 - make malloc UB with undef input
 - make malloc UB when most significant bit of size is undef
 - skip verification when most significant bit of size is 1 (add to Pre)
 - freeze input when it's undef (@aqjune's suggestion)

**Comment by aqjune** [comment]
Hmm, previously I voted for the 5th option, but now I think the second option (make malloc UB with undef input) would be the option that people like.
The reason is that it allows Attributor to propagate 'noundef' to the function declaration because there are many functions that look like this:

```
void do_something(i64 size) {
  %p = malloc(size)
  // work on %p
}
=>
void do_something(i64 noundef size) {
  %p = malloc(size)
  // work on %p
}
```

malloc is already raising UB on poison size, so this won't hurt code motion I believe.

Since the nonnull patch is almost landed, if the second option is okay, I'll prepare this patch as well.

**Comment by aqjune** [comment]
I'm working on this

**Comment by aqjune** [comment]
https://reviews.llvm.org/D97045

**Comment by nunoplopes** [comment]
The main issue is fixed, but llvm known_functions needs to be updated. Keep this open so we dont forget.

**Comment by aqjune** [comment]
I think it's okay to close this because the remaining functions updated by D97045 are not being approximated.
D97045 updated:
```
strndup
dunder_strndup
malloc
vec_malloc
realloc
vec_realloc
reallocf
aligned_alloc
calloc
vec_calloc
valloc
```
`dunder_strndup` and `strndup` are not being approximated yet, so okay.
The remaining calls are allocators, either updated in the new PR or not being approximated as well.
