### ISSUE TITLE
Parallelize the clang plugin

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#587]
Let's collect ideas so they don't get lost.

Some constraints:
 - Can't fork/create a thread on each SMT query: it's too expensive. It also makes production of error reports harder.
 - Probably we can't fork per function either

An idea is to change our plugin from runOnFunction() to runOnModule() so we get all functions at once. Then we can fork x processes and distribute the functions evenly (e.g., count number of instructions per function and try to balance these with a greedy algorithm).

The other concern is to avoid creating too many processes system-wide. One possibility is to roll our own coordinator, that would listen on a unix socket (or whatever) and receive requests for thread creation. Each plugin process would request a number of processes equal to the number of functions divided by 3 (some constant), for example. This is the max parallelism each plugin can cope with.
Then the coordinator replies with the max allowed number of processes the plugin can create.
The coordinator needs to recover from crashes in plugin processes and to distribute processes evenly across active plugin processes.
Rolling out this coordinator doesn't seem that tricky (famous last words).
We could shop around for coordinators. MacOS has its own thing (Grand Central Dispatch), but I dunno how well other OSs support that API. I don't even know if GCD is applicable to our case, since it seems it's mostly a thread pool, which is not exactly what we need.

@regehr had some ideas as well.

**Comment by regehr** [comment]
so it turns out that gnu make has a parallelism server and here is code that grabs a token from it and puts it back:
```
  int res = read(3, &c, 1);
  std::cout << "read: " << res <<  "\n";
  if (res == 1) {
    res = write(4, &c, 1);
    std::cout << "write: " << res <<  "\n";
  }
```
(here I've assumed that the pipe is available on fds 3 and 4, in real life this is not generally the case and you need to find them in an environment variable)

more info about this:
https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html
http://make.mad-scientist.net/papers/jobserver-implementation/

**Comment by regehr** [comment]
my working hypothesis is that we'll fork once for every TV request. the algorithm is:
- ask the jobserver for a token using a nonblocking read
- if we got a token, then there's a free core, so fork off a process which does the TV and puts results into a file; then, put the token back into the jobserver, and terminate
- if we did not get a token, just do TV in the main clang process

the only drawback I can see here is it'll fork too many times, but it is so appealingly simple that I plan to implement this and see how it performs before doing something that is trickier. with any luck this is dozens or at most a couple hundred lines of code.

**Comment by regehr** [comment]
something awkward about parallelism is that TV instances will complete out of order. @aqjune started to work on this here:
https://github.com/AliveToolkit/alive2/pull/513

there seem to be a few different things we could do:
1. create a very large number of output files (one per TV call) in the same directory
2. create a directory per translation unit and then in that directory, one file per TV call
3. preserve the current file structure, which as far as I can tell necessitates having the main clang process collect output from all of its children and then print it in the proper order

alternatively, I think it would be just fine to suppress output from TV successes. we don't learn anything from this. so what if we went with option #1 above, but only created a file when alive2 finds something wrong?

**Comment by regehr** [comment]
as expected, it is trivial to fork off the solver part of  alive2's work:

https://github.com/AliveToolkit/alive2/commit/c31cd972519b493988e30f857c80d67df64ed4ac

not yet solved are throttling parallelism properly (not difficult using gnu make's jobserver, mentioned above) and keeping output from getting all mixed up (probably best solved by having each process dump into a separate file and collating the results at the end)

**Comment by regehr** [comment]
ok, here's a really obnoxious idea for stitching the outputs back together: before forking, agree on a file name, then the parent emits an #include directive and the child emits the file to be included. after the TV run has finished, we use the C preprocessor to create the file as if there had not been parallelism. this is easy and will work.

**Comment by nunoplopes** [comment]
> my working hypothesis is that we'll fork once for every TV request. the algorithm is:
> 
> * ask the jobserver for a token using a nonblocking read
> * if we got a token, then there's a free core, so fork off a process which does the TV and puts results into a file; then, put the token back into the jobserver, and terminate
> * if we did not get a token, just do TV in the main clang process
> 
> the only drawback I can see here is it'll fork too many times, but it is so appealingly simple that I plan to implement this and see how it performs before doing something that is trickier. with any luck this is dozens or at most a couple hundred lines of code.

This algorithm sounds like you can end up with twice as many processes than cores because you still go ahead with TV even without a token. All TV executions should block until they get a token to avoid this issue.

BTW, what about using a global semaphore? (https://man7.org/linux/man-pages/man3/sem_open.3.html)
If MacOS supports them, it might be an easy way to do this. We would just need a simple program to initialize the semaphore with the number of cores (or a user-defined value).

**Comment by regehr** [comment]
I believe "every fork() is protected by a token acquisition" serves as a straightforward proof that this strategy creates the correct number of processes.

A global semaphore can definitely work (I did something similar in opt-fuzz) but it feels more elegant to interoperate with make-level parallelism. I'm going to do that first and will try the other thing if necessary.

**Comment by aqjune** [comment]
Would revamping #513 be helpful for this?
Maybe I can split the PR to smaller ones. The first one will be adding get_outs()/set_outs() API that gets/sets the out stream.

**Comment by regehr** [comment]
a small status update. for benchmarking I'm doing TV on this repo:
  https://github.com/regehr/rb_tree_demo

on my home machine using `make -j10`, TV of this repo takes 38.5 minutes using the current clang plugin

one thing I implemented is an "always fork" version of the clang plugin: it only runs TV in child processes, the main clang process doesn't use the solver. this reduces the `make -j10` time for TV of the repo above to 7.6 minutes, which I consider to be a solid result. actual concurrency is limited using GNU make's jobserver, so at most 10 total processes are running at any time, but the free-running main clang process can end up calling fork a huge number of times. most of those processes get blocked waiting for the jobserver, but they still exist and use up RAM. I suspect this could be a problem for a really huge project (of course we can't really do TV for huge projects anyway, so I don't think we need to worry about this in the short term).

to avoid the "too many blocked processes" problem I implemented another version that only forks a child when a jobserver token is available (we find this out using a non-blocking read). if no token is available, it simply runs TV in the main clang process as usual. this turns out to not work because fork() only forks the calling thread, leaving us without the worker thread pool that we recently added to Z3's scoped_timer. so the trivial implementation of this idea fails. Nuno suggested using pthread_atfork to get Z3 to shut down the thread pool and I'll work on that next.

I did not yet do any work on fixing up the order of output, right now it is all scrambled up by the concurrent processes. @aqjune I will look at your closed patch, thanks.

**Comment by regehr** [comment]
ok, the pthread_atfork() thing seems to work, but it turns out the "only sometimes fork" version of our clang plugin is slower than the original one (while still being much faster than the current never-fork version). I suspect this is what is happening:
- there's only one file being compiled (this happens frequently in practice, and definitely is the common case for my little repo above)
- all tokens are consumed, so clang runs Z3 in-process, getting unlucky and it's a slow verification problem
- the other 9 tokens are released by forked processes, but they were lucky and complete quickly, so now we have 9 unused cores and they can't be used until clang gets past the slow TV problem
as far as I can tell, this problem is inherent in the "sometimes fork" model.

so not sure what you guys want to do here. both of these versions improve upon what we currently have. we could merge one of them or let people choose which one they want (my current code makes it easy to switch between them).

Nuno, I assume that I should submit the atfork thing to Z3? do you want to look at my solution first? it's basically trivial but could easily be that I've missed a problem with it.

**Comment by nunoplopes** [comment]
Regarding pthread_atfork, the issue is windows, which is officially supported.
We need to understand if "fork" on windows is an issue, and if so what's the right API to fix the issue.

**Comment by nunoplopes** [comment]
Regarding parallelization, did you try the option that splits the functions across a set of processes?
smth like:
 - try to get `n` tokens, with n = number of functions
 - get `x <= n` tokens
 - split functions in `x` buckets. try to be lightly smart to avoid terrible imbalance
 - fork `x` processes
 - main process waits to join the processes; each process returns its token.

**Comment by regehr** [comment]
Windows doesn't have a native fork() at all, but rather a CreateProcess call that is more like fork+exec rolled into one. So I don't think we need to worry about this there -- the issue simply will not happen. Or are we talking about Cygwin? WSL? Some combination of these?

**Comment by regehr** [comment]
I do not believe that the clang plugin is the place to implement batching. No individual clang process has the knowledge that it needs in order to do a good job here, even using the jobserver.

If we are going to do batching, I want to do it correctly, which is to have a global (not per-clang) worker pool that takes work from all clang instances. This won't be hard once we have unparse-parse for alive IR, but it is impossible at the moment.

**Comment by regehr** [comment]
Earlier I referred to a problem with the jobserver, I will describe it now.

The jobserver works by having processes forked by make inherit a pair of file descriptors. You acquire a token by reading a byte from one of the fds, and you release it by writing a token to the other fd. Unfortunately, make closes these fds when it execs a subprogram that it doesn't think is a recursive instance of make. There are three workarounds:
- use an old version of GNU make that didn't close these fds (my Mac has a make 3.x that is old enough, but my Linux box has a make 4.x that closes the fds)
- hack make to not close the file descriptors, this is what I'm doing for now and it works fine
- alter the makefile to tell make that alivecc is actually a recursive make. you do this by invoking it as `+alivecc` instead of `alivecc`. I tested this and it works. this may be the best solution since we should be able to just run `make CC=+alivecc`

**Comment by regehr** [comment]
here is my proposal:
1. we'll merge a PR doing the simplest of the options I've described in this thread: the always-fork model. this will be optional so if it results in too much overhead for some use cases, people should just not use it for those. no problem.
2. independently, I work on an appropriate fix for Z3 involving pthread_atfork() and whatever we need to do on Windows
3. later, when we have unparse-parse for alive IR, I'll implement a solution using the current number of persistent worker processes

**Comment by nunoplopes** [comment]
> I do not believe that the clang plugin is the place to implement batching. No individual clang process has the knowledge that it needs in order to do a good job here, even using the jobserver.
> 
> If we are going to do batching, I want to do it correctly, which is to have a global (not per-clang) worker pool that takes work from all clang instances. This won't be hard once we have unparse-parse for alive IR, but it is impossible at the moment.

I think we are talking about different things. I'm not talking about gathering functions from different clang processes.
What I meant is to change our clang plugin to be called with a module rather than a function. At that point we can parallelize over sets of functions rather than forking to verify a single function. It's super simple AFAICT. There's no need to parse alive IR or anything like that as we get the whole LLVM module in memory.
A minor benefit of forking is that we don't need to translate LLVM IR -> Alive2 IR 2x times (as we do right now).

**Comment by nunoplopes** [comment]
> Windows doesn't have a native fork() at all, but rather a CreateProcess call that is more like fork+exec rolled into one. So I don't think we need to worry about this there -- the issue simply will not happen. Or are we talking about Cygwin? WSL? Some combination of these?

I agree that probably windows shouldn't need anything other #ifdefing the code. I don't know all the windows APIs though.
Cygwin/WSL should be just fine; they have pthread.

**Comment by regehr** [comment]
I'll submit a pull request to Z3 soon. I have a simple patch that appears to work.

> I think we are talking about different things. I'm not talking about gathering functions from different clang processes.
> What I meant is to change our clang plugin to be called with a module rather than a function. At that point we can parallelize over sets of functions rather than forking to verify a single function. It's super simple AFAICT. There's no need to parse alive IR or anything like that as we get the whole LLVM module in memory.

I agree this'll work, but it seems like quite a bit of trouble just to avoid some fork calls. The thing that's killing us slow functions and fork overhead just doesn't matter in that case. I'd prefer to do the easy thing that gives us a good speedup and revisit this later if alive becomes fast enough that the fork calls matter. 

> A minor benefit of forking is that we don't need to translate LLVM IR -> Alive2 IR 2x times (as we do right now).

Yes, I'm already skipping that part of the code, in the subprocess case!

**Comment by regehr** [comment]
so I was curious how fast fork() actually is on Linux. I wrote a test program that forks a child and then waits for it in a loop, and put this in our clang plugin (can't do this sort of thing in isolation since large processes fork slower than small ones). the cost of a fork/wait pair in this environment is about 6 milliseconds. so basically, as long as the average time taken for a TV call on a function pair is somewhat more than 6ms, forking for every TV call isn't particularly wasteful. so far, for real applications, the average time taken to do TV on a function pair is much, much longer than this. 

the message I take away here is that until alive2 gets significantly faster, forking off a new process for each TV call in the clang plugin is totally fine.
