### ISSUE TITLE
portability across multiple solvers

### ISSUE THREAD

**Issue by regehr** [AliveToolkit/alive2#589]
this is something that I'd like to see happen, sooner or later.
I'm curious what people think about smt-switch, is this something we could maybe use?
https://arxiv.org/pdf/2007.01374.pdf
https://github.com/makaimann/smt-switch
(note that it doesn't have Z3 yet but "should have this soon", will wait and see about this)

**Comment by aqjune** [comment]
I think it would be helpful for rapid prototyping of Alive2 with different solvers - Alive2 has its own wrapper in smt/ directory (Z3 only yet), but it seems smt-switch has extensive tests about their implementation to the various backend as well (https://github.com/makaimann/smt-switch/tree/master/tests), which is nice. If there is no technical problem, I guess using it would be helpful to quickly see how the SAT/UNSAT number changes.
To fully use the project, I think there are quite a few things to be resolved. They are using shared_ptr, which is expensive because shared_ptr's reference counting is lowered into atomic operations. Also, the arxiv paper states that quantifiers are not fully supported yet.

**Comment by nunoplopes** [comment]
I don't see this happening. Unless someone steps in and does the work, but I guess they don't need an open issue for that 😀
