### ISSUE TITLE
What do block_id and offset mean?

### ISSUE THREAD

**Issue by nikic** [AliveToolkit/alive2#634]
Looking at https://alive2.llvm.org/ce/z/2AF1GG, I don't understand why this is a value mismatch. We know that `%i` must be zero and thus `%p` null (otherwise `%g` is poison).

Is there any documentation for what the alive output means for memory operations? Should block_id be interpreted as a base-address, in which case block_id+offset in this case result in a null pointer? But that would make an allocated object wrap the address space.

**Comment by nikic** [comment]
Ah, I see now that the address corresponding to the block_id is listed separately, and in this case it just happens that block_id and address are the same. So what this is telling me is that while the result will be another null pointer, this null pointer may be based on a different allocated object (the one with block_id 1).

I wonder though, is that actually a miscompile in this particular case? As the null pointer has no associated address, and the %p pointer does, doesn't this strictly expand legal accesses on the resulting pointer?

**Comment by nunoplopes** [comment]
We don't have any documentation yet beyond what's in the couple of papers we have written. The memory model we use is described here: https://web.ist.utl.pt/nuno.lopes/pubs/llvmmem-oopsla18.pdf
And some slides: https://web.ist.utl.pt/nuno.lopes/pres/pointers-eurollvm18.pptx

Each memory allocation gets a distinct block id. This is what LLVM calls the base object/address. The offset is the offset in bytes from the base address of the corresponding object. For example:
```
p = malloc() // block_id=1, offset=0
q = malloc() // block_id=2, offset=0
r = gep p, 4 // block_id=1, offset=4
```

Give the alias analysis rules, gep can only change the offset, not the block id. So you can't produce a pointer to an object q starting from a pointer from object p. That's why `gep null, x` can never produce a dereferenceable pointer: the base object is null and no pointer created from null is dereferenceable.

In your example, the base address of block 1 is 1. Hence doing a `gep p, -1` gives a pointer to block_id=1, which corresponds to address 0. But this is not the same as the null pointer. See this:
```
p = malloc  // block_id = 1
p = gep p, x  // such that ptrtoint(p) == 0
p = gep p, -x // block_id=1, offset=0
*p = 1 // ok

q  = gep null, y // never dereferenceable
```

Hope this helps 😀  Please have a look at the slides I referenced above and let me know if you have further questions.
