### ISSUE TITLE
noescape pointer passed as argument

### ISSUE THREAD

**Issue by nunoplopes** [AliveToolkit/alive2#682]
If we pass a noescape pointer as argument to a caller that is nowrite, then it can't escape the pointer but can return it.
So a function may return a noescape pointer in a hidden way like this:
```llvm
define i8* g(i8* %p) nowrite {
  ret i8* %p
}

define i8 @f(i8* nocapture %p) {
  store i8 1, %p
  %q = call @g(%p)
  store %q, @glb  ;; escapes %p
...
}
```

If we inline `@g` it becomes clear that `@f` triggers UB. The question is whether this matters or whether we can ignore because of POR.

**Comment by aqjune** [comment]
I think it is okay for `@f` to assume that `@g` only returns a pointer without nocapture attribute.

Let's assume that there is a missed bug due to this assumption.
The missed bug would be 'Source is more defined than target' because the target's nocapture pointer (returned by `@g`) was escaped.
The source must have an equivalent `@g` call (otherwise, Alive2 would already have raised an error), and its returned pointer must not be escaped (otherwise, the source is UB).

This means that there is a divergence between the source and target's behavior; the target escapes some pointer whereas the source does not. Alive2 can assign a plain pointer and raise 'Memory mismatch' or etc.

**Comment by nunoplopes** [comment]
I guess the explanation is pretty simple: we can't pass a nocapture pointer as argument if it's not nocapture as well. Even if it's nowrite, it can still escape through ptr2int or by returning the ptr.
Should we make the following legal?
```llvm
define void @src(i8* nocapture %p) {
  call i8* @g(i8* %p)
  ret void
}

define void @tgt(i8* nocapture %p) {
  unreachable
}

declare i8* @g(i8*)
```

**Comment by aqjune** [comment]
I think so; if calling `@g(i8* %p)` isn't UB, it is allowed to attach nocapture to `%p` even if it is passed as an argument to a function that can potentially capture, which is fishy.
