### ISSUE TITLE
Add cmake package for alive2

### ISSUE THREAD

**Issue by archercreat** [AliveToolkit/alive2#904]
Hello! I decided to add cmake packaging for alive2 so people could find its libraries with `find_package` e.g.
```cmake
find_packge(alive2 CONFIG REQUIRED)
```` 
and link with them with `target_link_libraries`:
```cmake
target_link_libraries(${PROJECT_NAME} alive2::ir alive2::smt alive2::util)
```
So far everything works great except that normally one would include headers of a library like this: `#include <alive2/ir/memory.h`, but because alive2 uses `PROJECT_SOURCE_DIR` as a base include directory, all the directories are visible outside alive2 namespace. Im willing to refactor includes a bit so they are properly hidden but its better to ask you if you okay with this change.
Another question is: why `ir/`, `smt/` and other directories are made as separate libraries? Looking at dependencies graph they are tightly coupled and probably should be combined into one library:
![image](https://user-images.githubusercontent.com/41573188/235979131-523b494c-ed37-460b-8761-2908f789014f.png)
My goal is to make alive2 usable with `FetchContent` and `find_package` and although visible includes outside alive2 namespace are not an issue, it is better to hide them.

**Comment by nunoplopes** [comment]
I don't know what to reply, except that we accept reasonable PRs that don't change the whole codebase if they improve things for some use case.
Things are separated in different libraries for convenience, there's no other reason. But smt is special because it interacts with a 3rd party library (Z3). Anyway, unless there's a specific reason to change things, let's not change them.
