### ISSUE TITLE
Examples timing out

### ISSUE THREAD

**Issue by tanmaytirpankar** [AliveToolkit/alive2#916]
Hi,

The following examples and some similar ones are timing out locally and on the online instance. Is this expected? Adding the --disable-undef-input flag did not help. Reducing the bit width helped. Are these examples too big for Alive2?

```
define float @src(float %0) {
  %2 = fmul float %0, 1.000000
  ret float %2
}
define float @tgt(float %0) {
  ret float %0
}
```

AND

```
define i32 @src(i32 %0, i32 %1) {
  %3 = bitcast i32 %0 to float
  %4 = fmul float %3, 1.000000
  %5 = bitcast float %4 to i32
  ret i32 %5
}
define i32 @tgt(i32 %0, i32 %1) {
  ret i32 %0
}
```

**Comment by regehr** [comment]
yes, timeouts are expected for queries containing FP, the problem is Z3, not alive2. you should keep using the --disable-undef-input flag and then increase the timeout to something huge.

also, Zhengyang is working on support for optionally modeling floats using uninterpreted functions, but of course that sort of model won't work for queries like these. we're hoping it will help his superoptimizer make progress on optimizing FP queries that don't care about what the FP instructions are actually doing. 

you should also look at Juneyoung Lee's CAV paper about mlir-tv, where he played some interesting games with FP semantics that are more precise than a UF but less precise then the full circuit. I don't see why we couldn't use some of those tricks in alive2. Nuno may or may not be interested in merging this sort of stuff, but you and Zhengyang could collaborate on a fork of the repo.

**Comment by nunoplopes** [comment]
Right, this requires fundamental work that we haven't done yet. It's a know issue.
