### ISSUE TITLE
Can disable_undef_input (and similar) be made a property of TransformVerify?

### ISSUE THREAD

**Issue by manasij7479** [AliveToolkit/alive2#96]
I have to mix several verify calls where disable_undef_input is true for speed, and a last one where it is false to make sure the transformation generated by Souper is sound.
Changing global state for this seems like a bad idea.  
Should I submit a PR that makes this an option when constructing a TransformVerify object?
(Maybe a TransformVerifyOpts struct?)

**Comment by nunoplopes** [comment]
Well, it's complicated :)
It's true that it's fine to simply change the flag at verification time to get most of the performance benefits. But this flag also impacts the construction of the formula itself.  This is because the symbolic execution we do is more expensive if undef is on (it has to do a lot of rewriting).
So the API would be unsafe in the sense that if you would pass disable_undef_input=false to TransformVerify, but symbolic execution was run with the flag on, it would give incorrect results.
Same story for poison FWIW.
So the only way would be to drop the optimization in symbolic execution and pay the price for that.  Not sure it's worth it.
Any thoughts?

**Comment by manasij7479** [comment]
Complicated indeed.
Can the differences in symbolic execution be controlled with a switch variable?

**Comment by nunoplopes** [comment]
> Complicated indeed.
> Can the differences in symbolic execution be controlled with a switch variable?

It could, but my worry is the interaction between the calls to the symbolic execution and to the verification APIs. The user could pass invalid combinations of flags to these separate calls and we simply can't detect the issue.
That's why I'm not fond of changing the status quo. Your usage is an advanced one, so you should pay the price. We shouldn't make unsafe APIs available in general.
I'm happy to accept patches that 1) don't impact performance, and 2) make things at least not less safe than they are now :)

**Comment by nunoplopes** [comment]
Please reopen if you have further ideas and/or submit a patch. Thanks!
